version: "3.9"
services:
  quran-app:
    image: hzein86/quran-app:latest
    ports:
      - "5678:80"
    env_file:
      - .env
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any

